name: Docker Container

# The CI.yml action depends on a custom container with cmake, cmocka and so on.
# It is build here whenever the Dockerfile changes.

on:
  push:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/container.yml'
    branches: main
  pull_request:
    paths:
      - '.devcontainer/Dockerfile'
      - '.github/workflows/container.yml'
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: nikolodion
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Only Build
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          tags: nikolodion/tdd-platform:pr
        
      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          file: .devcontainer/Dockerfile
          push: true
          tags: nikolodion/tdd-platform:latest
